### PR TITLE
Contained view controller need to have their view's autoresizing disable...

### PR DESCRIPTION
**Pull request by jcoleman**
...d since we're manually laying out the view.

Otherwise if you push (or set as a placeholder) a UIViewController with a UIView that has the default autoresizing mask of flexible width/height then the autoresizing generates an incorrect layout in the landscape orientation.

### CODE REVIEW

**Comment by percysnoodle** [comment]
(a) I'm not sure I like doing this in layoutSubviews - I think I'd prefer to do it when the controller is pushed.
(b) Does setting the autoresizingMask to none stop the controller from automatically animating when the DDC is resized?  If so would we be better off setting translatesAutoresizingMaskIntoConstraints to no?

**Comment by jcoleman** [comment]
As to (a), I considered doing that instead but for two reasons: 1.) You'd have to duplicate it in the setters for placeholder controllers and the replace controller methods and 2.) I was considered about how it would work with view unloading (i.e., if I've pushed 5 controllers, and it's view gets unloaded and reloaded the next time we pop down to it, we need to make sure that the newly loaded view gets this set as well.)

As to (b), I don't believe so. All it does is mean that the view doesn't automatically get a new frame set. Also, setting `translatesAutoresizingMaskIntoConstraints` to `NO` I don't think would do the trick since if someone isn't using auto layout then my understanding would be that that would be a no-op right?

**Comment by percysnoodle** [comment]
Good points for (a).

For (b), setting translatesAutoresizingMaskIntoConstraints stops the view from creating constraints based on its autoresizingMask, though I don't know at what point this happens.  I _think_ the tick box in IB sets that property, and if so then yes, it would be a no-op.

Do you have a simple example that reproduces the landscape orientation bug?  I'd like to have a play with it so that I can understand the problem.

**Comment by jcoleman** [comment]
Yeah, so if someone wasn't using auto layout, then I don't think that at it would fix the issue to just disable those constraints being added.

As to a repro, it's very simple. In the demo project, replace the requisite app launch code with:

```
SGBDrillDownController *drillDownController = [[SGBDrillDownController alloc] init];

UIViewController* leftPlaceholderController = [[UIViewController alloc] init];
leftPlaceholderController.view.backgroundColor = [UIColor redColor];
leftPlaceholderController.view.autoresizingMask = UIViewAutoresizingNone;

drillDownController.leftPlaceholderController = leftPlaceholderController;

self.window.rootViewController = drillDownController;
```

**Comment by jcoleman** [comment]
Incidentally, I'm working on adding 1.) iOS 7 style swipe to navigate back functionality and 2.) iOS 6+ state restoration support. Hoping to have a PR on the first sometime today and on the second tomorrow.

**Comment by percysnoodle** [comment]
Sounds awesome - thanks!

**Comment by percysnoodle** [comment]
Just had a play with it - thanks for the example.  Ugh, autolayout.

Thanks for catching this one.

**Pull request merged**
