### PR TITLE
Ability to hide left view controller when on portrait orientation.

### PR DESCRIPTION
**Pull request by guilhermearaujo**
As I asked on issue #5, now implemented.

### CODE REVIEW

**Comment by percysnoodle** [comment]
That's great, thanks!

In order to more closely match the UISplitViewController, I'd prefer that the property be named shouldHideLeftViewControllerInPortraitOrientation.

If the user has set the leftControllerWidth to something other than 320, we should restore their setting when they go back to landscape.

What do you think we should do if the user hasn't got a right view controller?

**Comment by guilhermearaujo** [comment]
I'm ok with the method name. I can make a new variable to store the current width and the user-defined width.

About not having a right view controller, I'm not sure how to handle this situation. But why would someone use this without having both VCs in first place?

**Comment by guilhermearaujo** [comment]
~~I've just commited changes to fix the Autolayout issue described on issue # 7.~~

**Comment by percysnoodle** [comment]
Sorry to be a pain, but could we deal with the two issues separately?  I haven't yet tested whether the things that fix your autolayout setup break our non-autolayout setup.

**Comment by guilhermearaujo** [comment]
Sure, actually, I should have done that in first place. I just need to figure out how to remove this last commit from Github.

**Comment by percysnoodle** [comment]
Great, thanks!

You should be able to do something like:

```
git checkout mybranch
git reset --hard HEAD^
git push --force
```

Do make sure your commit's saved on another branch!

**Comment by guilhermearaujo** [comment]
Done, I will make a new branch for the autolayout issue.

**Comment by percysnoodle** [comment]
Thanks.

I've just had a look at the second commit, with the extra initialiser.  I think in we'd be better off saving the width whenever the user sets it, rather than making them do so in a special initialiser.

**Comment by guilhermearaujo** [comment]
It is going to be saved on both cases. User can set `leftControllerWidth` at any time, and the actual view width is determined by `currentLeftControllerWidth`. But do it as you wish, it's your work after all.

**Pull request closed without merging**
