### PR TITLE
Update SGBDrillDownController.m

### PR DESCRIPTION
**Pull request by svenresch**
Enhanced to improve UITableViewController based views with header view widths that may need an update when the container view width changes. A table header view in particular will not resize correctly unless we call to reload data.

### CODE REVIEW

**Comment by percysnoodle** [comment]
Have you checked the `autoresizingMask` on your header views? I use tables with header views in my app, and although I did have resizing issues at first I was able to fix it in the header view code.

More generally, I'm not keen to add special cases like this; if it's needed for `UITableViewController` then presumably it's also needed for other controllers with `UITableView`s, and what about `UICollectionViewController`, etc, etc...

If a user does need to hook in at this point, then I'd rather accomodate them by adding more notifications.

**Comment by svenresch** [comment]
Hey there Simon,

Yes I do have auto resizing setup. The problem is with resizing of UILabels that are nested within the header UIView. I have a UILabel in particular that is setup to auto resize and also to adjustsFontSizeToFitWidth. It's the label however that seems to be the problem as it did was not doing it's layout/painting correctly when a long enough string is set into it.

I understand how tying to a specific UITableView class is undesirable. If a notification was broadcast, with the affected view controller instance as a param, that should work nicely too.

**Comment by percysnoodle** [comment]
Could you give a bit more detail about your setup?  What are the contents of your `tableView:viewForHeaderAtIndexPath:` method? What is the `autoresizingMask` of the label?  What goes wrong with its layout?

**Comment by svenresch** [comment]
Something along the lines of this should work. Again the UILabel does not set it's fontSize to fit automagically unless a full reload is done.

<pre><code>
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    float h = 40.0f;
    float y = 10.0f;
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, tableView.frame.size.width, h)];
    view.autoresizingMask = UIViewAutoresizingFlexibleWidth;
    view.autoresizesSubviews = YES;
    view.backgroundColor = [UIColor clearColor];
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(10, y, tableView.frame.size.width-20, 20)];
    label.autoresizingMask = UIViewAutoresizingFlexibleWidth;
    label.backgroundColor = [UIColor clearColor];
    label.font = [UIFont boldSystemFontOfSize:18.0f];
    label.textAlignment = NSTextAlignmentCenter;
    label.adjustsFontSizeToFitWidth = YES;
    label.text = @"2012 Harley-Davidson Dyna Models";
    [view addSubview:label];
    return view;
}
</code></pre>

**Comment by percysnoodle** [comment]
If you put a breakpoint in that method, what's the size of the tableView when it's first called?

(also, you probably want to be using `tableView.bounds` rather than `tableView.frame`, since you're working in the tableview's coordinate space.

**Pull request closed without merging**
